export enum HttpResponse {
  OK = "OK",
  SERVER_ERROR = "internal server Error!",
  USER_EXIST = "User already exist",
  USER_CREATION_FAILED = "User Creation Failed, please try again",
  USER_NOT_FOUND = "User not Found",
  USER_BLOCKED = "User blocked",
  INVALID_CREDNTIALS = "Invalid Credentials",
  CREATED = "Created Successfully",
  LOGGED_IN_SUCCESSFULLY = "User Logged In Successfully",
  LOGGED_OUT = "User Logged Out",
  ACCESS_TOKEN_EXPIRED = "Access Token Expired",
  REFRESH_TOKEN_EXPIRED = "Refresh Token Expired",
  UNAUTHORIZED = "Unauthorized Access, Please Login First",
  TOKEN_NOT_FOUND = "Token not Found",
  ACCESS_DENIED = "Access Denied!",
  ITEM_EXIST = "Item Already Exist",
  INVALID_ID = `Invalid Id`,
  TAST_NOT_FOUND='Task not found',
  ACCESS_TOKEN_MISSING='Token is Missing',
  PLEASE_FILLOUT ='Please fillout all the field ( name, email , password)'
}
